Vagrant::Config.run do |config|
  config.vm.box = 'precise32'
  config.vm.customize do |vm|
    vm.memory_size = 768
  end

  config.vm.share_folder "10xeng_root", "/var/lib/10xeng", "."

  # temporary using for toolchain development
  #config.vm.share_folder "cli", "/cli", "/Users/radim/Projects/10xeng/10xengineer-node"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ['cookbooks', 'more_cookbooks']
    chef.data_bags_path = 'data_bags'
    chef.log_level = :debug
    chef.add_recipe 'apt'
    chef.add_recipe 'git'
    chef.add_recipe 'monit'
    chef.add_recipe 'node'
    chef.add_recipe 'lvm'
    chef.add_recipe 'lxc'
    chef.add_recipe 'lxc::rootfs-cache'
    chef.add_recipe 'mc-node::default'

    chef.json.merge!({
      :monit => {
      :start_delay => 15,
      :interval => 30,
      :web => {
      :enabled => true
    }}
    })

    #this prints out the vagrant config to a `dna.json` file that we
    #can upload to an EC2 instance and use with `chef-solo`.
    require 'json'
    open('dna.json', 'w') do |f|
      chef.json[:run_list] = chef.run_list
      f.write chef.json.to_json
    end
    open('.cookbooks_path.json', 'w') do |f|
      f.puts JSON.generate([chef.cookbooks_path].flatten.map{|x| File.expand_path(x)})
    end
  end
end
