module.exports.status = require("./status")
module.exports.pools = require("./pools")
module.exports.nodes = require("./nodes")
module.exports.machines = require("./machines")
module.exports.snapshots = require("./snapshots")
module.exports.templates = require("./templates")
module.exports.proxy_users = require("./proxy_users")