#!/bin/sh

PATH=~/.rbenv/shims:~/.rbenv/bin:$PATH

echo `pwd` | grep "gitolite-admin.git$"
if [ $? -eq 0 ]; then
  echo "gitolite-admin repository; skipping 10xlabs hooks"
else
  export GEM_HOME="$HOME/.gem/ruby/`ruby -e 'x=RUBY_VERSION;print(x=~/^1.8/ ? "1.8" : x)'`"
  export PATH="$PATH:$GEM_HOME/bin"
  
  ~/compilation/hooks/pre-receive.rb 

  exit $?
fi
