#!/bin/sh

PATH=~/.rbenv/shims:~/.rbenv/bin:$PATH

echo `pwd` | grep "gitolite-admin.git$"
if [ $? -eq 0 ]; then
  echo "gitolite-admin repository; skipping 10xlabs hooks"
else
  ~/compilation/hooks/pre-receive.rb

  exit $?
fi
