source 'http://rubygems.org'

gem "ffi-rzmq"
gem "yajl-ruby"
gem "facets"
gem "microcloud"

gem "foreman"

# TODO for stub commands only
gem "rest-client"

gem "vagrant"
gem "fog"
gem "net-ssh"

group :test do
  gem "rspec"
end

