source 'http://rubygems.org'

gem "ffi-rzmq"
gem "yajl-ruby"
gem "facets"
gem "microcloud"

gem "foreman"

# internal service storage
gem "mongoid", "~> 3.0.0.rc"

# TODO for stub commands only
gem "rest-client"

gem "vagrant"
gem "fog"
gem "net-ssh"
gem "uuid"

# git management
gem "grit"

# windows related
gem "winrm"

group :test do
  gem "rspec"
end

