// Generated by CoffeeScript 1.3.3
(function() {
  var everyone, log, nconf, nowjs, restify, routes, server;

  restify = require("restify");

  log = require("log4js").getLogger();

  nowjs = require("now");

  nconf = require("nconf");

  routes = require("./routes");

  nconf.env().argv();

  nconf.file({
    file: "server/config.json"
  });

  nconf.defaults({
    'NODE_ENV': 'development'
  });

  nconf.set('database:host', '127.0.0.1');

  nconf.set('database:port', 5984);

  console.log("NODE_ENV: " + nconf.get("NODE_ENV"));

  console.log("database:" + nconf.get("database"));

  server = module.exports = restify.createServer({
    name: "microcloud.10xengineer.me",
    version: "0.1.0"
  });

  server.use(restify.acceptParser(server.acceptable));

  server.use(restify.dateParser());

  server.use(restify.queryParser());

  server.use(restify.bodyParser());

  server.use(restify.throttle({
    burst: 100,
    rate: 50,
    ip: true,
    overrides: {
      "192.168.1.106": {
        rate: 0,
        burst: 0
      },
      "127.0.0.1": {
        rate: 0,
        burst: 0
      }
    }
  }));

  server.use(restify.conditionalRequest());

  routes.registerRoutes(server);

  everyone = nowjs.initialize(server);

  nowjs.on('connect', function() {
    this.now.channel = 'channel 1';
    nowjs.getGroup(this.now.channel).addUser(this.user.clientId);
    return log('Joined channel ' + this.now.name);
  });

  nowjs.on('disconnect', function() {
    return log('Left channel ' + this.now.name);
  });

  everyone.now.distributeMessage = function(message) {
    return nowjs.getGroup(this.now.channel).now.receiveMessage(this.now.name, message);
  };

  server.listen(8080, function() {
    return console.log("%s listening at %s", server.name, server.url);
  });

  server.get({
    url: "/admin"
  }, function(req, res, next) {
    return res.render("ADMIN PAGE TO GO HERE");
  });

}).call(this);
