#!/bin/bash
#
# 10xLab LXC bootstrap service for Ubuntu 12.04 LTS
#
# More information at http://10xlabs.net/
#
### BEGIN INIT INFO
# Provides:          10xlab-bootstrap
# Required-Start:    networking
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Initializes 10xLabs repository on a local machine
# Description:       Initializes 10xLabs repository on a local machine.
### END INIT INFO

. /lib/lsb/init-functions

exec > >(tee /var/log/10xlab-bootstrap.log) 2>&1

NAME=10xlab-bootstrap
ROOT=/var/10xlab
ENDPOINT=http://10.0.3.1:8000
JSON_PARSE=./json_parse.rb
GIT=/usr/bin/git
CHEF_SOLO=/usr/local/bin/chef-solo

function get_metadata()
{
	curl -s -o /tmp/bootstrap.meta ${ENDPOINT}/metadata
	curl -s -o /tmp/repository.tar.gz ${ENDPOINT}/repository
}

# bootstrap only the first time
if [ -f $ROOT/metadata.rb ]; then
	exit
fi

log_daemon_msg "Bootstrapping 10xLabs definition" ""
get_metadata

mkdir -p /var/10xlab
tar xvfz /tmp/repository.tar.gz -C /var/10xlab 1>/dev/null

gem install chef --no-ri --no-rdoc

# /etc/10xlab/bootstrap.rb
$CHEF_SOLO -c /etc/10xlab/bootstrap.rb -j /tmp/bootstrap.meta