#!/bin/bash
#
# 10xLab LXC bootstrap service for Ubuntu 12.04 LTS
#
# More information at http://10xlabs.net/
#
### BEGIN INIT INFO
# Provides:          10xlab-bootstrap
# Required-Start:    networking
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Initializes 10xLabs repository on a local machine
# Description:       Initializes 10xLabs repository on a local machine.
### END INIT INFO

. /lib/lsb/init-functions

exec > >(tee /var/log/10xlab-bootstrap.log) 2>&1

NAME=10xlab-bootstrap
ROOT=/var/10xlab
METADATA=http://10.0.3.1/instance
JSON_PARSE=./json_parse.rb
GIT=/usr/bin/git
CHEF_SOLO=/usr/local/bin/chef-solo

function get_metadata()
{
	#
	# FIXME hardcoded metadata (retrieve from local ENDPOINT)
	#
	# - START ------------------------------------------------------
	cat >/tmp/bootstrap.meta <<-EOH
{
	"repo": "ssh://tenx@bunny.laststation.net:440/263f0030-d317-012f-e1b2-58b035f9777f",
	"run_list": ["recipe[git]", "recipe[ruby]", "recipe[nginx]"],
	"microcloud": {
    	"endpoint": "http://bunny.laststation.net:8080/"
    }
}
	EOH
	# - END --------------------------------------------------------
}

# bootstrap only the first time
if [ -f $ROOT/metadata.rb ]; then
	exit
fi

log_daemon_msg "Bootstrapping 10xLabs definition" ""
get_metadata

# download repository
curl -o /tmp/repository.tar.gz http://10.0.3.1:8000/repository

mkdir -p /var/10xlab
tar xvfz /tmp/repository.tar.gz -C /var/10xlab

gem install chef --no-ri --no-rdoc

# /etc/10xlab/bootstrap.rb
$CHEF_SOLO -c /etc/10xlab/bootstrap.rb -j /tmp/bootstrap.meta